"""Website copy and curated media for each game; release facts come from the catalog.

Screenshots reference inspected frames under docs/evidence so the pages show
the shipping builds rather than mock-ups. Keep claims aligned with the release
notes in docs/ and the About text in each game.
"""

EVIDENCE = 'docs/evidence'

GAMES = {
    'warband': {
        'tagline': 'A snappy real-time strategy skirmish in the classic mould.',
        'summary': ('Gather gold and lumber, raise a base, train an army and raze the rival settlement. '
                    'Matches take ten to twenty minutes against an AI that plays a recognisable strategy, '
                    'or against a friend over the internet.'),
        'online': {
            'mode': 'Two-player competitive match',
            'text': ('Two seats per room. Create a room, send the code or invitation link to your friend, and the '
                     'match starts when you both connect. The server runs the simulation; a dropped connection '
                     'pauses the match and reconnects automatically.'),
            'retention': 'Rooms stay open for 15 minutes without both players.',
        },
        'features': [
            'Seven units with real roles: peasants, footmen, archers, scouts, knights, catapults and clerics.',
            'Nine buildings, nine upgrades and a short tech chain; peasants repair what the enemy leaves standing.',
            'Settlement planning: queue buildings, units and upgrades without selecting a worker.',
            'Idle peasants find safe work on their own; construction plans borrow gatherers after delivery.',
            'Procedural maps in three sizes and three lands with meadows, groves, ponds and stone.',
            'Three AI difficulties for offline games with two to four factions; autosave every two minutes.',
            'Original procedural art and music: every sprite, sound and track is generated by the game.',
        ],
        'first_match': [
            'Let your peasants gather. Gold and lumber totals are at the top of the screen.',
            'In the Settlement row choose Build → Farm and click clear ground near your base.',
            'Build a Barracks, then Train → Footman. Requests wait until they can be paid.',
            'Select your soldiers, press A and click towards the enemy to attack-move.',
            'Eliminate every enemy unit and building to win.',
        ],
        'screenshots': [
            (f'{EVIDENCE}/warband-art-2026-09-08/10_battle.png', 'A pitched battle between two armies outside a farm row'),
            (f'{EVIDENCE}/warband-art-2026-09-08/06_settlement_normal.png', 'A settlement with every building type and unit role'),
            (f'{EVIDENCE}/warband-map-workers-2026-09-08/settlement/09-active-production.png', 'The Plans panel listing construction and training'),
            (f'{EVIDENCE}/warband-art-2026-09-08/08_lumber_camp.png', 'Peasants chopping wood beside a lumber mill'),
        ],
        'requirements': {
            'windows': 'Windows 10 or 11, 64-bit, with OpenGL 3.3 graphics drivers. About 120 MB on disk.',
            'macos': 'macOS 14 or later on Apple Silicon (M1 or newer). About 90 MB on disk.',
        },
        'known_issues': [
            'The installer is unsigned and the Mac app is not notarized; see the first-launch notes above.',
            'The layout uses a fixed logical canvas; fullscreen helps readability on small screens.',
            'Large offline maps with three or four players can run past twenty minutes without a decision.',
            'English only.',
        ],
        'guide': 'https://github.com/ikamensh/saga2d/blob/main/docs/warband-play-together.md',
        'data_dir': {'windows': '%USERPROFILE%\\.warband', 'macos': '~/.warband'},
    },
    'tribes': {
        'tagline': 'A compact turn-based strategy game on an isometric island.',
        'summary': ('Lead a tribe across a small isometric map: found cities, research technologies, harvest '
                    'the land and outfight rival tribes within thirty rounds. Every action has a hotkey and '
                    'a match fits in a lunch break.'),
        'online': {
            'mode': 'Two-player competitive match',
            'text': ('Two human tribes take alternating turns on a server-owned map. Create a room, share the '
                     'code, and play at your own pace; the turn waits for you while you are connected.'),
            'retention': 'Rooms stay open for 15 minutes without both players.',
        },
        'features': [
            'Cities, parks, technologies, territory and a surviving army all count towards the final score.',
            'A tech tree that changes how you harvest, move and fight.',
            'AI tribes that recruit, research and concede when they cannot rebuild.',
            'High scores recorded locally, with a results screen that explains every point.',
            'Keyboard-first controls: the keycaps on screen show every shortcut.',
        ],
        'first_match': [
            'Select your warrior with Enter and move it to explore the island.',
            'Press T to open the technology list and pick the first research.',
            'Capture neutral villages with C to grow your tribe.',
            'End your turn with E; the game shows whose turn it is at the top.',
            'Hold the most cities and the largest empire when round 30 ends.',
        ],
        'screenshots': [
            (f'{EVIDENCE}/online-multiplayer-public-2026-09-07/tribes-match.png', 'An online match seen from the Ember tribe'),
            (f'{EVIDENCE}/multiplayer-2026-09-06/tribes-title.png', 'The Tribes title screen'),
            (f'{EVIDENCE}/multiplayer-2026-09-06/tribes-result.png', 'A results screen with the final standings'),
        ],
        'requirements': {
            'windows': 'Windows 10 or 11, 64-bit, with OpenGL 3.3 graphics drivers.',
            'macos': 'macOS 14 or later on Apple Silicon (M1 or newer).',
        },
        'known_issues': [
            'The installer is unsigned and the Mac app is not notarized; see the first-launch notes above.',
            'Online matches are two human tribes only; offline games add AI tribes.',
            'English only.',
        ],
        'guide': 'https://github.com/ikamensh/saga2d/blob/main/docs/online-multiplayer.md',
        'data_dir': {'windows': '%USERPROFILE%\\.tribes', 'macos': '~/.tribes'},
    },
    'shardbound': {
        'tagline': 'An Eador-inspired campaign of provinces, heroes and hex battles.',
        'summary': ('Lead one of four heroes and a persistent army through a linked campaign of three shards. '
                    'Develop your stronghold, investigate guarded sites, counter a rival expedition and '
                    'command turn-based hex battles where veterans keep their experience.'),
        'online': {
            'mode': 'Two-player shared-realm co-op',
            'text': ('You and a friend command the same realm and army. Either of you can build, explore and '
                     'give battle orders; the server keeps one authoritative campaign. Campaign rooms are kept '
                     'for seven days without both players, so you can continue tomorrow.'),
            'retention': 'Campaign rooms are kept for 7 days without both players.',
        },
        'features': [
            'Four heroes with two advancement disciplines each, ten troop roles and twelve relics.',
            'Guarded expeditions with rout, hold and extraction objectives across twelve authored patterns.',
            'Manual orders or optional automatic rounds, with skippable playback of the resolved actions.',
            'A three-shard linked campaign: choose the next challenge and which veterans and relics travel.',
            'Three world themes, seed selection and three difficulty settings.',
            'Manual saves, rolling autosaves, sound controls, reduced motion and larger reading text.',
        ],
        'first_match': [
            'Open the Field Guide with F1 for your first turns; the Codex (C) holds every rule.',
            'Build a marketplace to fund your army and recruit troops at your stronghold.',
            'Explore the current province with X and inspect the rival plan with V.',
            'Invade a neighbouring province and fight the hex battle, or let automatic rounds resolve it.',
            'Capture Duskspire before the rival takes Westwatch.',
        ],
        'screenshots': [
            (f'{EVIDENCE}/shardbound-distribution-2026-09-08/mac-package/portable-smoke-shard.png', 'The Frontier shard with the province map and stronghold'),
            (f'{EVIDENCE}/shardbound-distribution-2026-09-08/mac-package/portable-smoke-battle.png', 'A hex battle for Silverford'),
            (f'{EVIDENCE}/shardbound-distribution-2026-09-08/mac-package/portable-smoke-codex.png', 'The Codex rules reference'),
            (f'{EVIDENCE}/shardbound-distribution-2026-09-08/mac-package/portable-smoke-rival.png', 'The rival expedition plan'),
        ],
        'requirements': {
            'windows': 'Windows 10 or 11, 64-bit, with OpenGL 3.3 graphics drivers.',
            'macos': 'macOS 14 or later on Apple Silicon (M1 or newer).',
        },
        'known_issues': [
            'A development preview: balance, onboarding and presentation are still being evaluated, and the app uses a development icon.',
            'The installer is unsigned and the Mac app is not notarized; see the first-launch notes above.',
            'Co-op shares one realm; there is no competitive online mode yet.',
            'English only.',
        ],
        'guide': 'https://github.com/ikamensh/saga2d/blob/main/eador/README.md',
        'data_dir': {'windows': '%USERPROFILE%\\.shardbound', 'macos': '~/.shardbound'},
    },
}

SUPPORT_URL = 'https://github.com/ikamensh/saga2d/issues'
SOURCE_URL = 'https://github.com/ikamensh/saga2d'
